apiVersion: apps/v1
kind: Deployment
metadata:
  name: sedekahje-be
  namespace: sedekahjer
  annotations:
    app.kubernetes.io/version: "20250331.010504"  # This will be updated by GitHub Actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sedekahje-be
  template:
    metadata:
      labels:
        app: sedekahje-be
    spec:
      containers:
      - name: sedekahje-be
        image: ghcr.io/farhan-helmy/sedekahje-be:20250331.010504
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mongo-uri
      imagePullSecrets:
      - name: ghcr-secret